name: nn_mal
dependencies:
- python=3.6
- numpy
- pandas
- pip:
  - pybloomfiltermmap
  - losswise
  - sklearn
  - lief
  - scipy
  - http://download.pytorch.org/whl/torch-0.3.0.post4-cp36-cp36m-macosx_10_7_x86_64.whl
  - torchvision